### ISSUE TITLE
Getting error "The attribute @thi was not present in the provided roll data."

### ISSUE THREAD

**Issue by RollToSaveVsDragons** [drexl93/pf2e-lockpicking#1]
I'm pretty sure I had this working earlier, but now whenever the player clicks the okay button, this error appears.
The player has Legendary Thievery and Thieves Tools
Foundry 0.7.5
PF2e 1.10.15.2210

**Comment by drexl93** [comment]
Hey, would you mind uninstalling the module and reinstalling it, and seeing if it's fixed now? I just pushed another bug fix and it may be related.

**Comment by RollToSaveVsDragons** [comment]
I reinstalled and now it works, but I still get the same UI warning.

**Comment by drexl93** [comment]
Hmmm that's weird. Alright, would you mind exporting that character and sending me the JSON file on Discord? My handle is Some Knucklehead#4725
